---
title: "Globalization and Compensation"
author: "Nicholas Ray"
date: "6/9/2023"
output: html_document
---
```{r libraries,message=FALSE,warning=FALSE,include=FALSE}
library(here);library(readxl);library(cowplot);library(zoo);library(plm);
library(lmtest);library(pcse);library(pdynmc);library(stargazer);library(Amelia);
library(panelr);library(tidyverse)
```
```{r data,message=FALSE,warning=FALSE,include=FALSE}
spending<-read.csv(
  here("data","spending","SOCX_AGG_07062023164135366.csv")
  )
wages<-read_csv(
  here("data","wages","DP_LIVE_07062023164354304.csv")
  )
imports<-read_csv(
  here("data","imports","DP_LIVE_10062023180219881.csv")
  )
quintile1<-read_excel(
  here("data","income","API_SI.DST.FRST.20_DS2_en_excel_v2_5455995.xls"),
  col_names=TRUE, skip=2
  )
quintile2<-read_excel(
  here("data","income","API_SI.DST.02ND.20_DS2_en_excel_v2_5463348.xls"),
  col_names=TRUE, skip=2
  )
quintile3<-read_excel(
  here("data","income","API_SI.DST.03RD.20_DS2_en_excel_v2_5467057.xls"),
  col_names=TRUE, skip=2
  )
```
```{r cleaning}
country_codes<-c("AUS","AUT","BEL","CAN","CZE","DEU","DNK","ESP","FIN","FRA","GBR",
             "IRL","ISL","ITA","JPN","KOR","LUX","MEX","NLD","NZL","POL","PRT",
             "SVK","USA") #based on the majority of available data for "spending", minus Norway
# and Sweden due to "wages" lacking that data
################################################################################
# net total (public and private) social spending in percentage of GDP
spending<-spending %>%
  rename(country_code=COUNTRY,year=Year,spending=Value) %>%
  select(country_code,year,spending) %>%
  subset(country_code %in% country_codes)
################################################################################
# "low pay" wages, or the share of workers earning less than two-thirds of median earnings
wages<-wages %>%
  rename(country_code=LOCATION,year=TIME,wages=Value) %>%
  select(country_code,year,wages) %>%
  subset(country_code %in% country_codes)
################################################################################
# annual imports as a percentage of GDP (proxy for economic globalization)
imports<-imports %>%
  rename(country_code=LOCATION,year=TIME,imports=Value) %>%
  select(country_code,year,imports) %>%
  subset(country_code %in% country_codes)
################################################################################
# income quintiles over time (1 being lowest 20% and so on)
# to find the share of income for the lower half of the distribution: 1+2+(0.5*3) = lower ~50%
# then subtract that from 50 to get the amount of compensation needed, in terms of national income
# can then directly compare it to social spending?
quintile1<-quintile1 %>%
  pivot_longer(5:67,names_to = "year",values_to = "quintile1") %>%
  rename(country=`Country Name`,country_code=`Country Code`) %>%
  select(country,country_code,year,quintile1) %>%
  mutate(year=as.numeric(year)) %>%
  filter(year > "1994") %>%
  subset(country_code %in% country_codes)
quintile2<-quintile2 %>%
  pivot_longer(5:67,names_to = "year",values_to = "quintile2") %>%
  rename(country_code=`Country Code`) %>%
  select(country_code,year,quintile2) %>%
  mutate(year=as.numeric(year)) %>%
  filter(year > "1994") %>%
  subset(country_code %in% country_codes)
quintile3<-quintile3 %>%
  pivot_longer(5:67,names_to = "year",values_to = "quintile3") %>%
  rename(country_code=`Country Code`) %>%
  select(country_code,year,quintile3) %>%
  mutate(year=as.numeric(year)) %>%
  filter(year > "1994") %>%
  subset(country_code %in% country_codes)
################################################################################
data<-full_join(imports,quintile1,by=c("country_code","year")) %>%
  full_join(.,quintile2,by=c("country_code","year")) %>%
  full_join(.,quintile3,by=c("country_code","year")) %>%
  full_join(.,wages,by=c("country_code","year")) %>%
  full_join(.,spending,by=c("country_code","year"))
data<-data %>%
  group_by(country,year) %>%
  mutate(spending_need=spending/wages,income=quintile1+quintile2+quintile3,
         income2=60-income)
```
```{r figures}
figure<-panel_data(data,id = country_code,wave = year) %>%
  line_plot(spending,
            overlay = FALSE,
            add.mean = TRUE)
figure2<-figure + geom_line(mapping=aes(y=income2))
```